version: '3.8'

services:
  mysql-server:
    image: mysql:8.0
    container_name: zabbix-mysql-server
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql-server:mysql-server
    restart: always
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    networks:
      - zabbix-net
    depends_on:
      - mysql-server
      
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    restart: always
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
      - PHP_TZ=Asia/Jakarta
    networks:
      - zabbix-net
    depends_on:
      - mysql-server
      - zabbix-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    networks:
      - zabbix-net
    depends_on:
      - zabbix-server

networks:
  zabbix-net:
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
